angular.module('marketplace.templates', []).run(['$templateCache', function($templateCache) {
  $templateCache.put("scripts/components/bids/bidsView.html",
    "<div class=container><div class=row><div class=col-md-12>Propostas entrarão nesse espaço</div></div></div>");
  $templateCache.put("scripts/components/campaigns/campaignsView.html",
    "<div class=container><div class=row><div class=col-md-12>As campanhas serão mostradas aqui</div></div></div>");
  $templateCache.put("scripts/components/purchases/purchasesView.html",
    "<div class=container><div class=row><div class=col-md-12>Suas últimas compras</div></div></div>");
  $templateCache.put("scripts/components/search/searchMenuView.html",
    "<div class=panel-group id=accordion><div class=\"panel panel-default\"><div class=panel-heading><h4 class=panel-title><a data-toggle=collapse data-parent=#accordion href=#collapseNewspappers><span>Jornais</span></a></h4></div><div id=collapseNewspappers class=\"panel-collapse collapse in\"><div class=list-group><a href=# class=list-group-item>Estadão <span class=\"badge pull-right\">11</span></a> <a href=# class=list-group-item>Folha <span class=\"badge pull-right\">9</span></a> <a href=# class=list-group-item>O Globo <span class=\"badge pull-right\">5</span></a> <a href=# class=list-group-item>The New York Times <span class=\"badge pull-right\">1</span></a></div></div></div><div class=\"panel panel-default\"><div class=panel-heading><h4 class=panel-title><a data-toggle=collapse data-parent=#accordion href=#collapseRegions><span>Área de Atuação</span></a></h4></div><div id=collapseRegions class=\"panel-collapse collapse in\"><div class=list-group><a href=# class=list-group-item>São Paulo <span class=\"badge pull-right\">103</span></a> <a href=# class=list-group-item>Rio de Janeiro <span class=\"badge pull-right\">53</span></a> <a href=# class=list-group-item>Ceará <span class=\"badge pull-right\">14</span></a></div></div></div><div class=\"panel panel-default\"><div class=panel-heading><h4 class=panel-title><a data-toggle=collapse data-parent=#accordion href=#collapseWeekdays><span>Dia da Semana</span></a></h4></div><div id=collapseWeekdays class=\"panel-collapse collapse in\"><div class=list-group><a href=# class=list-group-item>Segunda <span class=\"badge pull-right\">2</span></a> <a href=# class=list-group-item>Terça <span class=\"badge pull-right\">1</span></a> <a href=# class=list-group-item>Quarta <span class=\"badge pull-right\">2</span></a> <a href=# class=list-group-item>Quinta <span class=\"badge pull-right\">3</span></a> <a href=# class=list-group-item>Sexta <span class=\"badge pull-right\">6</span></a> <a href=# class=list-group-item>Sábado <span class=\"badge pull-right\">12</span></a> <a href=# class=list-group-item>Domingo <span class=\"badge pull-right\">22</span></a></div></div></div></div>");
  $templateCache.put("scripts/components/search/searchView.html",
    "<div class=\"container search-results\"><div class=row><div class=col-md-3><search-menu></search-menu></div><div class=col-md-9><div class=section><form action=\"\"><div class=input-group><label for=search class=sr-only>Busca</label><input id=search name=search class=\"form-control input-lg\" placeholder=\"Digite a região, área de atuação ou qualquer termo e busque!\"> <span class=input-group-btn><button class=\"btn btn-primary input-lg\" type=button>Buscar</button></span></div></form></div><div class=\"section row\"><div class=col-md-6><div class=\"panel panel-default\"><div class=panel-body><div class=media><a href=# class=media-left><img src=http://placehold.it/130x100 alt=\"\"></a><div class=media-body><h4 class=media-heading>Estadão</h4>Caderno: Esportes<br>Formato: Meia Página<br>Dias da Semana: Domingos<br>Cor: Cromia</div></div></div><div class=panel-footer>R$ <span class=price>5.000,00</span> <button type=button class=\"btn btn-primary\">Adicionar</button></div></div></div><div class=col-md-6><div class=\"panel panel-default\"><div class=panel-body><div class=media><a href=# class=media-left><img src=http://placehold.it/130x100 alt=\"\"></a><div class=media-body><h4 class=media-heading>O Globo</h4><span class=\"label label-default\">Caderno</span> Brasil<br><span class=\"label label-default\">Formato</span> Rodapé Alto<br><span class=\"label label-default\">Dia</span> Segundas<br><span class=\"label label-default\">Cor</span> PB</div></div></div><div class=panel-footer>R$ <span class=price>5.000,00</span> <button type=button class=\"btn btn-primary\">Adicionar</button></div></div></div></div><div class=\"section row\"><div class=col-md-6><div class=\"panel panel-default\"><div class=panel-body><div class=media><a href=# class=media-left><img src=http://placehold.it/130x100 alt=\"\"></a><div class=media-body><h4 class=media-heading>Folha de São Paulo</h4><span class=\"label label-default\">Caderno</span> Ilustrada<br><span class=\"label label-default\">Formato</span> Meia Página<br><span class=\"label label-default\">Dia</span> Domingos<br><span class=\"label label-default\">Cor</span> Cromia</div></div></div><div class=panel-footer>R$ <span class=price>5.000,00</span> <button type=button class=\"btn btn-primary\">Adicionar</button></div></div></div><div class=col-md-6><div class=\"panel panel-default\"><div class=panel-body><div class=media><a href=# class=media-left><img src=http://placehold.it/130x100 alt=\"\"></a><div class=media-body><h4 class=media-heading>Extra</h4>Caderno: Política<br>Formato: Anúncio 3 x 12,7<br>Dias da Semana: Terças<br>Cor: Cromia</div></div></div><div class=panel-footer>R$ <span class=price>5.000,00</span> <button type=button class=\"btn btn-primary\">Adicionar</button></div></div></div></div></div></div></div>");
  $templateCache.put("scripts/libs/angular-bootstrap/accordion.html",
    "<div ng-controller=AccordionCtrl><p><button class=\"btn btn-default btn-sm\" ng-click=\"status.open = !status.open\">Toggle last panel</button> <button class=\"btn btn-default btn-sm\" ng-click=\"status.isFirstDisabled = ! status.isFirstDisabled\">Enable / Disable first panel</button></p><label class=checkbox><input type=checkbox ng-model=oneAtATime> Open only one at a time</label><accordion close-others=oneAtATime><accordion-group heading=\"Static Header, initially expanded\" is-open=status.isFirstOpen is-disabled=status.isFirstDisabled>This content is straight in the template.</accordion-group><accordion-group heading={{group.title}} ng-repeat=\"group in groups\">{{group.content}}</accordion-group><accordion-group heading=\"Dynamic Body Content\"><p>The body of the accordion group grows to fit the contents</p><button class=\"btn btn-default btn-sm\" ng-click=addItem()>Add Item</button><div ng-repeat=\"item in items\">{{item}}</div></accordion-group><accordion-group is-open=status.open><accordion-heading>I can have markup, too! <i class=\"pull-right glyphicon\" ng-class=\"{'glyphicon-chevron-down': status.open, 'glyphicon-chevron-right': !status.open}\"></i></accordion-heading>This is just some content to illustrate fancy headings.</accordion-group></accordion></div>");
  $templateCache.put("scripts/shared/aboutView.html",
    "<p>This is the about view.</p>");
  $templateCache.put("scripts/shared/footer/footerView.html",
    "<div class=container><span class=\"ficon ficon-heart\"></span> Predicta &amp; Direct &copy; 2014</div>");
  $templateCache.put("scripts/shared/header/headerView.html",
    "<div class=container><div class=row><div class=col-md-12><h3>Marketplace</h3></div></div></div>");
  $templateCache.put("scripts/shared/mainView.html",
    "<div class=container><div class=jumbotron><h1>'Allo, 'Allo!</h1><p class=lead><img src=images/yeoman.png alt=\"I'm Yeoman\"><br>Always a pleasure scaffolding your apps.</p><p><a class=\"btn btn-lg btn-success\" ng-href=#>Splendid!<span class=\"glyphicon glyphicon-ok\"></span></a></p></div><div class=\"row marketing\"><h4>HTML5 Boilerplate</h4><p>HTML5 Boilerplate is a professional front-end template for building fast, robust, and adaptable web apps or sites.</p><h4>Angular</h4><p>AngularJS is a toolset for building the framework most suited to your application development.</p><h4>Karma</h4><p>Spectacular Test Runner for JavaScript.</p></div></div>");
  $templateCache.put("scripts/shared/nav/navView.html",
    "<nav class=\"navbar navbar-default\" role=navigation><div class=container><div class=navbar-header><button type=button class=\"navbar-toggle collapsed\" data-toggle=collapse data-target=#navbar aria-expanded=false aria-controls=navbar><span class=sr-only>Toggle navigation</span> <span class=icon-bar></span> <span class=icon-bar></span> <span class=icon-bar></span></button></div><div ng-controller=NavCtrl class=\"collapse navbar-collapse\" id=navbar><ul class=\"nav navbar-nav\"><li ng-class=\"{ active:isActive('/search') }\"><a href=#/search>Busca</a></li><li ng-class=\"{ active:isActive('/purchases') }\"><a href=#/purchases>Últimas compras</a></li><li ng-class=\"{ active:isActive('/bids')}\"><a href=#/bids>Propostas</a></li><li ng-class=\"{ active:isActive('/campaigns') }\"><a href=#/campaigns>Campanhas</a></li></ul></div></div></nav>");
}]);
